using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class PortGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new PortGroupReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not PortGroupReceiver receiver) return;
            foreach (var entry in receiver.PortGroupTypes)
            {
                EmitFor(context, entry.Symbol, entry.GroupAttribute);
            }
        }

        private static void EmitFor(GeneratorExecutionContext context, INamedTypeSymbol typeSymbol, AttributeData groupAttr)
        {
            // groupAttr 已在 SyntaxReceiver 阶段定位，避免在 Execute 重复扫描 GetAttributes()。
            var groupName = groupAttr.ConstructorArguments[0].Value?.ToString() ?? $"{typeSymbol.Name}Ports";
            var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
            var typeName = typeSymbol.Name;

            // 走单次成员遍历 + 单次属性扫描，避免 LINQ Where/Any 多重枚举。
            var members = typeSymbol.GetMembers();
            var ports = new List<IPropertySymbol>(members.Length);
            for (int i = 0; i < members.Length; i++)
            {
                if (members[i] is not IPropertySymbol prop) continue;
                var attrs = prop.GetAttributes();
                for (int j = 0; j < attrs.Length; j++)
                {
                    if (attrs[j].AttributeClass?.Name == "PortAttribute")
                    {
                        ports.Add(prop);
                        break;
                    }
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Hevo.Charting;");
            sb.AppendLine("using Hevo.Charting.LowCode;");
            sb.AppendLine("using Hevo.Charting.WorkFlow;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // §root-cause-fix 2026-05-13:这里以前是 `public readonly struct {groupName}`,
            // 但 struct 的 `new T()`(零参)永远走隐式 zero-init,**完全绕过用户的 [CallerMemberName]
            // 默认参 ctor**,导致所有 DataPort 字段是 null。下游 FastSourceMapIngestor.Process 拿
            // null port 去 board.WriteIfChanged → TypedBucketMap.TryGetValue(null) → ArgumentNullException →
            // Select 内部 catch → Plot.onError → 业务 Plot.onNext 永远不 fire → _latestBoard 永远 null →
            // ProjectAll 永远 bail → 所有 feature 的 OnProject 都跑不起来 → 蜡烛图永远空白。
            //
            // 改 sealed class 后,`new T()` 规规矩矩调到 [CallerMemberName] 那条 ctor,port 字段
            // 在 ctor body 里正常初始化。代价:每个 PortGroup 实例多一次堆分配(几十字节),schema
            // 级字段持有一份,在所有用法里都摊销可忽略。换来零踩 C# struct ctor 暗坑。
            //
            // 不走 "struct + 显式 parameterless ctor" 那条路是因为 C# 10+ 才允许,demo project
            // LangVersion=9.0,拖一票 csproj 跟着升不值。
            sb.AppendLine($"    public sealed class {groupName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {groupName} Default = new {groupName}(\"\");");
            sb.AppendLine();

            foreach (var port in ports)
            {
                var type = port.Type.ToDisplayString();
                sb.AppendLine($"        public readonly DataPort<ReadOnlyMemory<{type}>> {port.Name}Port;");
            }

            sb.AppendLine();
            sb.AppendLine($"        public {groupName}([CallerMemberName] string prefix = \"\")");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!string.IsNullOrEmpty(prefix)) {");
            sb.AppendLine("                if (prefix.EndsWith(\"Ports\")) prefix = prefix.Substring(0, prefix.Length - 5);");
            sb.AppendLine("                if (!prefix.EndsWith(\"_\")) prefix += \"_\";");
            sb.AppendLine("            }");
            foreach (var port in ports)
            {
                var type = port.Type.ToDisplayString();
                sb.AppendLine($"            {port.Name}Port = new DataPort<ReadOnlyMemory<{type}>>(prefix + \"{port.Name}\");");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine();
            sb.AppendLine($"    public static class {typeName}StreamExtensions");
            sb.AppendLine("    {");

            sb.AppendLine($"        public static ScatterConfigurator<TSource, {typeName}> AutoMap<TSource>(");
            sb.AppendLine($"            this ScatterConfigurator<TSource, {typeName}> cfg, ");
            sb.AppendLine($"            {groupName} ports)");
            sb.AppendLine($"            where TSource : BufferedDataSource<TSource, {typeName}>");
            sb.AppendLine("        {");
            foreach (var port in ports)
            {
                sb.AppendLine($"            cfg.Map(ports.{port.Name}Port, static (item, _) => item.{port.Name});");
            }
            sb.AppendLine("            return cfg;");
            sb.AppendLine("        }");

            sb.AppendLine($"        public static ScatterConfigurator<TSource, {typeName}> AutoMap<TSource>(");
            sb.AppendLine($"            this ScatterConfigurator<TSource, {typeName}> cfg)");
            sb.AppendLine($"            where TSource : BufferedDataSource<TSource, {typeName}>");
            sb.AppendLine("        {");
            sb.AppendLine($"            return cfg.AutoMap({groupName}.Default);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{namespaceName}.{typeName}.{groupName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // (Symbol, GroupAttribute) 元组：一次性记下 Group 属性，省去 Execute 阶段重复 GetAttributes 扫描。
        internal readonly struct PortGroupEntry
        {
            public readonly INamedTypeSymbol Symbol;
            public readonly AttributeData GroupAttribute;
            public PortGroupEntry(INamedTypeSymbol symbol, AttributeData groupAttribute)
            {
                Symbol = symbol;
                GroupAttribute = groupAttribute;
            }
        }

        private sealed class PortGroupReceiver : ISyntaxContextReceiver
        {
            public List<PortGroupEntry> PortGroupTypes { get; } = new();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is not TypeDeclarationSyntax tds || tds.AttributeLists.Count == 0) return;
                if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol symbol) return;

                var attrs = symbol.GetAttributes();
                for (int i = 0; i < attrs.Length; i++)
                {
                    if (attrs[i].AttributeClass?.Name == "PortGroupAttribute")
                    {
                        PortGroupTypes.Add(new PortGroupEntry(symbol, attrs[i]));
                        return;
                    }
                }
            }
        }
    }
}
