using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class PortGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 抓取所有带有 [PortGroup] 的类或结构体
            var sourceNodes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetSemanticTarget(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(sourceNodes, static (spc, source) => Execute(spc, source!));
        }

        private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;
            return symbol?.GetAttributes().Any(a => a.AttributeClass?.Name == "PortGroupAttribute") == true ? symbol : null;
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol typeSymbol)
        {
            var groupAttr = typeSymbol.GetAttributes().First(a => a.AttributeClass?.Name == "PortGroupAttribute");
            var groupName = groupAttr.ConstructorArguments[0].Value?.ToString() ?? $"{typeSymbol.Name}Ports";
            var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
            var typeName = typeSymbol.Name;

            var ports = typeSymbol.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "PortAttribute"))
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Hevo.Charting;");
            sb.AppendLine("using Hevo.Charting.LowCode;");
            sb.AppendLine("using Hevo.Charting.WorkFlow;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // 💥 产物 1：生成智能引脚组 (保持不变)
            sb.AppendLine($"    public readonly struct {groupName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {groupName} Default = new {groupName}(\"\");");
            sb.AppendLine();

            foreach (var port in ports)
            {
                var type = port.Type.ToDisplayString();
                sb.AppendLine($"        public readonly DataPort<ReadOnlyMemory<{type}>> {port.Name}Port;");
            }

            sb.AppendLine();
            sb.AppendLine($"        public {groupName}([CallerMemberName] string prefix = \"\")");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!string.IsNullOrEmpty(prefix)) {");
            sb.AppendLine("                if (prefix.EndsWith(\"Ports\")) prefix = prefix.Substring(0, prefix.Length - 5);");
            sb.AppendLine("                if (!prefix.EndsWith(\"_\")) prefix += \"_\";");
            sb.AppendLine("            }");
            foreach (var port in ports)
            {
                var type = port.Type.ToDisplayString();
                sb.AppendLine($"            {port.Name}Port = new DataPort<ReadOnlyMemory<{type}>>(prefix + \"{port.Name}\");");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            // 💥 产物 2：生成一键路由映射扩展 (全面升级 0-GC 与链式支持)
            sb.AppendLine();
            sb.AppendLine($"    public static class {typeName}StreamExtensions");
            sb.AppendLine("    {");

            // 💥 升级重载 1：增加 TSource 泛型推断，返回自身以支持无限连写
            sb.AppendLine($"        public static ScatterConfigurator<TSource, {typeName}> AutoMap<TSource>(");
            sb.AppendLine($"            this ScatterConfigurator<TSource, {typeName}> cfg, ");
            sb.AppendLine($"            {groupName} ports)");
            sb.AppendLine($"            where TSource : DataSource<TSource, {typeName}>");
            sb.AppendLine("        {");
            foreach (var port in ports)
            {
                // 💥 绝杀：直接生成 static 匿名函数，丢弃不需要的大管家状态 _，完美零 GC！
                // (注：这里取消了 defVal，因为底层 0-GC 的 FastSourceMapIngestor 已经是全量密级覆盖，不再需要初始化的默认值了)
                sb.AppendLine($"            cfg.Map(ports.{port.Name}Port, static (item, _) => item.{port.Name});");
            }
            sb.AppendLine("            return cfg; // 👈 返回构建器，支持继续连写 MapWindow 或 Compute！");
            sb.AppendLine("        }");

            // 💥 升级重载 2：单数据源极简映射
            sb.AppendLine($"        public static ScatterConfigurator<TSource, {typeName}> AutoMap<TSource>(");
            sb.AppendLine($"            this ScatterConfigurator<TSource, {typeName}> cfg)");
            sb.AppendLine($"            where TSource : DataSource<TSource, {typeName}>");
            sb.AppendLine("        {");
            sb.AppendLine($"            return cfg.AutoMap({groupName}.Default);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{namespaceName}.{typeName}.{groupName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
