using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    /// <summary>
    /// 编译期为带 [RequiredTrait(typeof(X))] 的 partial Layer 类生成 ValidateRequiredTraits 强类型 override。
    /// 运行时无反射、无装箱:只是几个内联的 data.Get&lt;X&gt;() == null 比对,首屏开销可忽略不计。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class RequiredTraitValidatorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidate(s),
                    transform: static (ctx, _) => GetTarget(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(classDeclarations, static (spc, info) => Emit(spc, info!));
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax cls
                && cls.Modifiers.Any(m => m.ValueText == "partial")
                && cls.AttributeLists.Count > 0;
        }

        private static GenInfo? GetTarget(GeneratorSyntaxContext ctx)
        {
            var cls = (ClassDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
            if (symbol == null) return null;

            var requiredTraits = new List<string>();
            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "RequiredTraitAttribute") continue;
                if (attr.ConstructorArguments.Length == 0) continue;
                if (attr.ConstructorArguments[0].Value is INamedTypeSymbol traitType)
                {
                    requiredTraits.Add(traitType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }
            if (requiredTraits.Count == 0) return null;

            string typeParameters = symbol.TypeParameters.IsEmpty
                ? ""
                : "<" + string.Join(", ", symbol.TypeParameters.Select(t => t.Name)) + ">";

            return new GenInfo(
                NamespaceName: symbol.ContainingNamespace.ToDisplayString(),
                ClassName: symbol.Name,
                ClassNameWithGenerics: symbol.Name + typeParameters,
                RequiredTraits: requiredTraits);
        }

        private static void Emit(SourceProductionContext ctx, GenInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 由 RequiredTraitValidatorGenerator 生成。");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.NamespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {info.ClassNameWithGenerics}");
            sb.AppendLine("    {");
            sb.AppendLine("        protected override void ValidateRequiredTraits(global::Hevo.Charting.Abstractions.IVisualData data)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.Collections.Generic.List<string>? missing = null;");
            foreach (var trait in info.RequiredTraits)
            {
                string shortName = ShortName(trait);
                sb.AppendLine($"            if (data.Get<{trait}>() == null) (missing ??= new global::System.Collections.Generic.List<string>()).Add(\"{shortName}\");");
            }
            sb.AppendLine("            if (missing != null)");
            sb.AppendLine($"                throw new global::System.InvalidOperationException(");
            sb.AppendLine($"                    \"Layer '\" + Name + \"' ({info.ClassName}) 缺少必需 trait: [\" + string.Join(\", \", missing) + \"]。请检查相关 Feature 是否被装配。\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"{info.ClassName}_RequiredTraits.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string ShortName(string fullyQualified)
        {
            int idx = fullyQualified.LastIndexOf('.');
            return idx >= 0 ? fullyQualified.Substring(idx + 1) : fullyQualified;
        }

        private record GenInfo(string NamespaceName, string ClassName, string ClassNameWithGenerics, List<string> RequiredTraits);
    }
}
