using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class RequiredTraitValidatorGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not Receiver receiver) return;
            foreach (var info in receiver.Hits) Emit(context, info);
        }

        private static GenInfo? Inspect(GeneratorSyntaxContext ctx)
        {
            var cls = (ClassDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
            if (symbol == null) return null;

            var requiredTraits = new List<string>();
            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "RequiredTraitAttribute") continue;
                if (attr.ConstructorArguments.Length == 0) continue;
                if (attr.ConstructorArguments[0].Value is INamedTypeSymbol traitType)
                {
                    requiredTraits.Add(traitType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }
            if (requiredTraits.Count == 0) return null;

            string typeParameters = symbol.TypeParameters.IsEmpty
                ? ""
                : "<" + string.Join(", ", symbol.TypeParameters.Select(t => t.Name)) + ">";

            return new GenInfo(
                NamespaceName: symbol.ContainingNamespace.ToDisplayString(),
                ClassName: symbol.Name,
                ClassNameWithGenerics: symbol.Name + typeParameters,
                RequiredTraits: requiredTraits);
        }

        private static void Emit(GeneratorExecutionContext ctx, GenInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.NamespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {info.ClassNameWithGenerics}");
            sb.AppendLine("    {");
            sb.AppendLine("        protected override void ValidateRequiredTraits(global::Hevo.Charting.Abstractions.IVisualData data)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.Collections.Generic.List<string>? missing = null;");
            foreach (var trait in info.RequiredTraits)
            {
                string shortName = ShortName(trait);
                sb.AppendLine($"            if (data.Get<{trait}>() == null) (missing ??= new global::System.Collections.Generic.List<string>()).Add(\"{shortName}\");");
            }
            sb.AppendLine("            if (missing != null)");
            sb.AppendLine($"                throw new global::System.InvalidOperationException(");
            sb.AppendLine($"                    \"Layer '\" + Name + \"' ({info.ClassName}) 缺少必需 trait: [\" + string.Join(\", \", missing) + \"]。请检查相关 Feature 是否被装配。\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"{info.ClassName}_RequiredTraits.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string ShortName(string fullyQualified)
        {
            int idx = fullyQualified.LastIndexOf('.');
            return idx >= 0 ? fullyQualified.Substring(idx + 1) : fullyQualified;
        }

        private sealed class Receiver : ISyntaxContextReceiver
        {
            public List<GenInfo> Hits { get; } = new();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is not ClassDeclarationSyntax cls) return;
                if (!cls.Modifiers.Any(m => m.ValueText == "partial")) return;
                if (cls.AttributeLists.Count == 0) return;
                var info = Inspect(context);
                if (info != null) Hits.Add(info);
            }
        }

        private record GenInfo(string NamespaceName, string ClassName, string ClassNameWithGenerics, List<string> RequiredTraits);
    }
}
