using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class TraitExtensionGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax c && c.BaseList != null,
                    // 核心修改：使用新的扫描逻辑
                    transform: static (ctx, _) => GetConsumedTraitsFromMethodBody(ctx))
                .Where(static m => m != null && m.Any());

            context.RegisterSourceOutput(classDeclarations.Collect(), GenerateCode!);
        }

        // ==========================================
        // 💥 核心修改：直接扫描 OnUpdate 里的 Get<T>()
        // ==========================================
        private static IEnumerable<INamedTypeSymbol>? GetConsumedTraitsFromMethodBody(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var semanticModel = context.SemanticModel;

            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
                return null;

            // 查找名为 OnUpdate 的方法
            var onUpdateMethod = classDeclaration.Members
                .OfType<MethodDeclarationSyntax>()
                .FirstOrDefault(m => m.Identifier.Text == "OnUpdate");

            if (onUpdateMethod == null) return null;

            var traits = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

            // 遍历方法体内的所有方法调用 (InvocationExpression)
            var invocations = onUpdateMethod.DescendantNodes().OfType<InvocationExpressionSyntax>();
            foreach (var invocation in invocations)
            {
                // 寻找类似 data.Get<GridStyleTrait>() 的结构
                if (invocation.Expression is MemberAccessExpressionSyntax memberAccess &&
                    memberAccess.Name is GenericNameSyntax genericName &&
                    genericName.Identifier.Text == "Get")
                {
                    // 提取尖括号里的类型 GridStyleTrait
                    var typeSyntax = genericName.TypeArgumentList.Arguments.FirstOrDefault();
                    if (typeSyntax != null)
                    {
                        var typeInfo = semanticModel.GetTypeInfo(typeSyntax);
                        if (typeInfo.Type is INamedTypeSymbol traitSymbol)
                        {
                            traits.Add(traitSymbol);
                        }
                    }
                }
            }

            return traits.Any() ? traits : null;
        }

        private static void GenerateCode(SourceProductionContext context, ImmutableArray<IEnumerable<INamedTypeSymbol>> traitGroups)
        {
            var uniqueTraits = traitGroups
                    .SelectMany(t => t)
                    .GroupBy(t => t.OriginalDefinition, SymbolEqualityComparer.Default)
                    .Select(g => g.Key as INamedTypeSymbol)
                    .Where(t => t != null)
                    .ToList();

            if (!uniqueTraits.Any()) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Hevo.Charting.Core;");
            sb.AppendLine("using Hevo.Charting.Abstractions;");
            sb.AppendLine();
            sb.AppendLine("namespace Hevo.Charting");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AutoGeneratedTraitExtensions");
            sb.AppendLine("    {");

            foreach (var trait in uniqueTraits)
            {
                if(trait == null)
                {
                    continue;
                }
                var traitName = trait.Name;
                var traitFullName = trait.ToDisplayString();
                var methodName = traitName.EndsWith("Trait") ? traitName.Substring(0, traitName.Length - 5) : traitName;

                var typeParams = trait.IsGenericType
                    ? string.Join(", ", trait.TypeParameters.Select(p => p.Name))
                    : "";

                string methodGenericArgs = string.IsNullOrEmpty(typeParams) ? "<TLayer>" : $"<TLayer, {typeParams}>";

                // 注意：这里依然保留对 IConsumes 的泛型约束，确保类型安全
                sb.AppendLine($"        public static VisualProxy<TLayer> {methodName}{methodGenericArgs}(");
                sb.AppendLine($"            this VisualProxy<TLayer> proxy, {traitFullName} trait)");
                sb.AppendLine($"            where TLayer : IChartLayer, IConsumes<{traitFullName}>");
                sb.AppendLine("        {");
                sb.AppendLine("            return proxy.PublishData(trait);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TraitExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
