using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class TraitConsumerGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not Receiver receiver) return;
            foreach (var info in receiver.Hits)
            {
                Emit(context, info);
            }
        }

        private static ClassGenerateInfo? Inspect(GeneratorSyntaxContext context)
        {
            var classSyntax = (ClassDeclarationSyntax)context.Node;
            var semanticModel = context.SemanticModel;

            var classSymbol = semanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
            if (classSymbol == null) return null;

            var onUpdateMethod = classSyntax.Members
                .OfType<MethodDeclarationSyntax>()
                .FirstOrDefault(m => m.Identifier.Text == "OnUpdate");

            if (onUpdateMethod == null) return null;

            var traits = new HashSet<string>();

            var invocations = onUpdateMethod.DescendantNodes().OfType<InvocationExpressionSyntax>();
            foreach (var invocation in invocations)
            {
                var symbolInfo = semanticModel.GetSymbolInfo(invocation);
                if (symbolInfo.Symbol is IMethodSymbol methodSymbol)
                {
                    var returnType = methodSymbol.ReturnType;
                    bool isVisualTrait = returnType.TypeKind != TypeKind.Interface &&
                                         returnType.AllInterfaces.Any(i => i.Name == "IVisualTrait");
                    if (isVisualTrait)
                    {
                        traits.Add(returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    }
                }
            }

            var attributes = classSyntax.AttributeLists.SelectMany(al => al.Attributes);
            foreach (var attr in attributes)
            {
                if (attr.Name.ToString().Contains("Consumes") && attr.ArgumentList != null)
                {
                    var arg = attr.ArgumentList.Arguments.FirstOrDefault()?.Expression;
                    if (arg is TypeOfExpressionSyntax typeOfExpr)
                    {
                        var typeSymbol = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;
                        if (typeSymbol != null)
                        {
                            traits.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                        }
                        else
                        {
                            traits.Add(typeOfExpr.Type.ToString());
                        }
                    }
                }
            }

            if (traits.Count == 0) return null;

            string typeParameters = classSymbol.TypeParameters.IsEmpty
                ? ""
                : "<" + string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name)) + ">";

            string classNameWithGenerics = classSymbol.Name + typeParameters;
            string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            return new ClassGenerateInfo(namespaceName, classNameWithGenerics, classSymbol.Name, traits);
        }

        private static void Emit(GeneratorExecutionContext context, ClassGenerateInfo info)
        {
            var interfaces = string.Join(",\n        ",
                info.Traits.Select(t => $"global::Hevo.Charting.Abstractions.IConsumes<{t}>"));

            string sourceCode = $@"// <auto-generated />
using System;

namespace {info.NamespaceName}
{{
    public partial class {info.ClassNameWithGenerics} :
        {interfaces}
    {{
    }}
}}
";
            context.AddSource($"{info.BaseClassName}_Consumes.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxContextReceiver
        {
            public List<ClassGenerateInfo> Hits { get; } = new();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is not ClassDeclarationSyntax classSyntax) return;
                if (!classSyntax.Modifiers.Any(m => m.ValueText == "partial")) return;
                var info = Inspect(context);
                if (info != null) Hits.Add(info);
            }
        }
    }

    internal record ClassGenerateInfo(string NamespaceName, string ClassNameWithGenerics, string BaseClassName, HashSet<string> Traits);
}
