using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hevo.Charting.CodeAnalysis
{
    [Generator(LanguageNames.CSharp)]
    public class TraitExtensionGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not Receiver receiver) return;
            EmitAll(context, receiver.AllTraits);
        }

        private static void Inspect(GeneratorSyntaxContext context, HashSet<INamedTypeSymbol> sink)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            if (classDeclaration.BaseList == null) return;

            var semanticModel = context.SemanticModel;
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol) return;

            var onUpdateMethod = classDeclaration.Members
                .OfType<MethodDeclarationSyntax>()
                .FirstOrDefault(m => m.Identifier.Text == "OnUpdate");

            if (onUpdateMethod == null) return;

            var invocations = onUpdateMethod.DescendantNodes().OfType<InvocationExpressionSyntax>();
            foreach (var invocation in invocations)
            {
                if (invocation.Expression is MemberAccessExpressionSyntax memberAccess &&
                    memberAccess.Name is GenericNameSyntax genericName &&
                    genericName.Identifier.Text == "Get")
                {
                    var typeSyntax = genericName.TypeArgumentList.Arguments.FirstOrDefault();
                    if (typeSyntax != null)
                    {
                        var typeInfo = semanticModel.GetTypeInfo(typeSyntax);
                        if (typeInfo.Type is INamedTypeSymbol traitSymbol)
                        {
                            sink.Add(traitSymbol);
                        }
                    }
                }
            }
        }

        private static void EmitAll(GeneratorExecutionContext context, HashSet<INamedTypeSymbol> traits)
        {
            var uniqueTraits = traits
                .GroupBy(t => t.OriginalDefinition, SymbolEqualityComparer.Default)
                .Select(g => g.Key as INamedTypeSymbol)
                .Where(t => t != null)
                .ToList();

            if (!uniqueTraits.Any()) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Hevo.Charting.Core;");
            sb.AppendLine("using Hevo.Charting.Abstractions;");
            sb.AppendLine();
            sb.AppendLine("namespace Hevo.Charting");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AutoGeneratedTraitExtensions");
            sb.AppendLine("    {");

            foreach (var trait in uniqueTraits)
            {
                if (trait == null) continue;
                var traitName = trait.Name;
                var traitFullName = trait.ToDisplayString();
                var methodName = traitName.EndsWith("Trait") ? traitName.Substring(0, traitName.Length - 5) : traitName;

                var typeParams = trait.IsGenericType
                    ? string.Join(", ", trait.TypeParameters.Select(p => p.Name))
                    : "";

                string methodGenericArgs = string.IsNullOrEmpty(typeParams) ? "<TLayer>" : $"<TLayer, {typeParams}>";

                sb.AppendLine($"        public static VisualProxy<TLayer> {methodName}{methodGenericArgs}(");
                sb.AppendLine($"            this VisualProxy<TLayer> proxy, {traitFullName} trait)");
                sb.AppendLine($"            where TLayer : IChartLayer, IConsumes<{traitFullName}>");
                sb.AppendLine("        {");
                sb.AppendLine("            return proxy.PublishData(trait);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TraitExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxContextReceiver
        {
            public HashSet<INamedTypeSymbol> AllTraits { get; } =
                new(SymbolEqualityComparer.Default);

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is ClassDeclarationSyntax c && c.BaseList != null)
                {
                    Inspect(context, AllTraits);
                }
            }
        }
    }
}
